# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
 api_type: "zhipuai"
 model: "glm-4"
 base_url: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
 api_key: "296f6869b992f5864a591e82c68ba8e2.YoNopUsXVEXgi8WU"